name: 'build-prefilght'
description: 'Action to perform all prefilght checks before building a lesson'
author: 'Robert P. Davey'
inputs:
  CACHE_VERSION:
    description: 'Optional renv cache version override'
    required: false
    default: ''

outputs:
  do-build:
    description: 'Do build?'
    value: ${{ steps.build-check.outputs.push_or_pr }}
  renv-needed:
    description: 'Is renv needed?'
    value: ${{ steps.renv-check.outputs.renv-needed }}
  renv-cache-hashsum:
    description: 'renv cache hashsum'
    value: ${{ steps.renv-check.outputs.renv-cache-hashsum }}

runs:
  using: "composite"
  steps:
    - name: "Is renv required?"
      id: renv-check
      uses: carpentries/actions/renv-checks@main
      with:
        CACHE_VERSION: ${{ inputs.CACHE_VERSION || '' }}
        skip-cache-check: true

    - name: "Get workflow artifact if Apply Cache trigger"
      id: get-apply-cache-artifact
      if: |
        github.event_name == 'workflow_run' &&
        steps.renv-check.outputs.renv-needed
      uses: carpentries/actions/download-workflow-artifact@main
      with:
        run: ${{ github.event.workflow_run.id }}
        name: 'apply-cache-result'

    - name: "Get apply cache result"
      id: get-apply-cache-result
      if: |
        github.event_name == 'workflow_run' &&
        steps.renv-check.outputs.renv-needed &&
        steps.get-apply-cache-artifact.outputs.success == 'true'
      run: |
        unzip apply-cache-result.zip
        echo "apply_cache_result=$(<./apply-cache-result)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Should we run build and deploy?"
      id: build-check
      if: always()
      run: |
        # ðŸ”§ Pre-build checks #
        if [[ "${{ github.event_name }}" == "schedule" ||
              "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "âœ… Scheduled or manual trigger. Build will run."
          echo "push_or_pr=true" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "workflow_run" &&
                "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
          if [[ "${{ github.event.workflow_run.event }}" == "pull_request" ]] ; then
            PRE_PR="${{ github.event.workflow_run.pull_requests[0].number }}"
            if [[ -n "$PRE_PR" ]]; then
              PR_DATA=$(gh pr view "$PRE_PR" --repo "${{ github.repository }}" --json merged,state)
              MERGED=$(echo "$PR_DATA" | jq -r '.merged')
              STATE=$(echo "$PR_DATA" | jq -r '.state')

              if [[ "$MERGED" == "false" || "$STATE" != "MERGED" ]]; then
                echo "â—PR not merged or in an invalid state. No build will run."
                echo "## â— Build Skipped" >> $GITHUB_STEP_SUMMARY
                echo "PR not merged or in an invalid state. No build will run." >> $GITHUB_STEP_SUMMARY
                echo "push_or_pr=false" >> $GITHUB_OUTPUT
              else
                echo "âœ… PR merged successfully. Build will run."
                echo "push_or_pr=true" >> $GITHUB_OUTPUT
              fi
            else
              if [[ "${{ steps.renv-check.outputs.renv-needed }}" == 'true' &&
                    (
                      "${{ steps.get-apply-cache-artifact.outputs.success }}" != "true" ||
                      "${{ steps.get-apply-cache-result.outputs.apply_cache_result }}" != "true"
                    ) ]]; then
                echo "â›” Apply Cache workflow required but failed. No build will run."
                echo "## â›” Build Skipped" >> $GITHUB_STEP_SUMMARY
                echo "Apply Cache workflow required but failed. No build will run." >> $GITHUB_STEP_SUMMARY
                echo "push_or_pr=false" >> $GITHUB_OUTPUT
              else
                echo "âœ… PR merged successfully. Build will run."
                echo "push_or_pr=true" >> $GITHUB_OUTPUT
              fi
            fi
          else
            if [[ "${{ steps.renv-check.outputs.renv-needed }}" == 'true' &&
                  (
                    "${{ steps.get-apply-cache-artifact.outputs.success }}" != "true" ||
                    "${{ steps.get-apply-cache-result.outputs.apply_cache_result }}" != "true"
                  ) ]]; then
              echo "â›” Apply Cache workflow required but failed. No build will run."

              echo "## â›” Build Skipped" >> $GITHUB_STEP_SUMMARY
              echo "Apply Cache workflow required but failed. No build will run." >> $GITHUB_STEP_SUMMARY

              echo "push_or_pr=false" >> $GITHUB_OUTPUT
            else
              echo "âœ… Triggered from workflow run. Build will run."
              echo "push_or_pr=true" >> $GITHUB_OUTPUT
            fi
          fi
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          PRE_PR=$(gh pr list --repo "${{ github.repository }}" --state merged --search "${{ github.sha }}" --json number -q ".[0].number") >> $GITHUB_ENV

          if [[ -n "$PRE_PR" ]]; then
            LABELS=$(gh pr view "$PRE_PR" --repo "${{ github.repository }}" --json labels -q ".labels[].name")
            if echo "$LABELS" | grep -q "type: package cache"; then
              echo "â›” Package cache update PR merged. Build will not run."

              echo "## â›” Build Skipped" >> $GITHUB_STEP_SUMMARY
              echo "Package cache update PR merged. Build will not run." >> $GITHUB_STEP_SUMMARY

              echo "push_or_pr=false" >> $GITHUB_OUTPUT
            elif echo "$LABELS" | grep -q "type: docker version"; then
              echo "â›” Workbench Docker version PR merged. Build will not run."

              echo "## â›” Build Skipped" >> $GITHUB_STEP_SUMMARY
              echo "Workbench Docker version PR merged. Build will not run." >> $GITHUB_STEP_SUMMARY

              echo "push_or_pr=false" >> $GITHUB_OUTPUT
            elif echo "$LABELS" | grep -q "type: workflows"; then
              echo "â›” Workflow file update PR merged. Build will not run."

              echo "## â›” Build Skipped" >> $GITHUB_STEP_SUMMARY
              echo "Workflow file update PR merged. Build will not run." >> $GITHUB_STEP_SUMMARY

              echo "push_or_pr=false" >> $GITHUB_OUTPUT
            else
              echo "âœ… Valid PR merged. Build will run."
              echo "push_or_pr=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "âœ… Direct push to main. Build will run."
            echo "push_or_pr=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "â—This was not a schedule or valid trigger. No build will run."

          echo "## â— Build Skipped" >> $GITHUB_STEP_SUMMARY
          echo "â—This was not a schedule or valid trigger. No build will run." >> $GITHUB_STEP_SUMMARY

          echo "push_or_pr=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
