name: "Update Workflows"
description: "Update GitHub Action Workflows for {sandpaper} repoisitories"
inputs:
  version:
    description: "Version of {sandpaper} to use"
    required: false
    default: 'current'
  repo:
    description: "CRAN-like repository to get the workflow files (no slash at end)"
    required: false
    default: "https://carpentries.r-universe.dev"
  clean:
    description: "Workflow file extensions to be cleaned before update. No wildcards as they will be auto-expanded. Defaults to none."
    required: false
    default: ''
outputs:
  old: 
    description: "old version of {sandpaper}"
    value: "${{ steps.update.outputs.old }}"
  new:
    description: "new version of {sandpaper}"
    value: "${{ steps.update.outputs.new }}"
  date:
    description: "date of the most recent update attempt"
    value: "${{ steps.update.outputs.date }}"
runs:
  using: "composite"
  steps:
    - name: "Update Workflows"
      id: update
      run: |
        ${{ github.action_path }}/update-workflows.sh \
          ${{ inputs.version }} \
          ${{ inputs.repo }} \
          ${{ inputs.clean }}
      shell: bash
