name: "Update Workflows"
description: "Update GitHub Action Workflows for Workbench lesson repoisitories"
inputs:
  version:
    description: "Version of workbench-workflows to use. 'release' for latest release, 'main' for main branch, or specific version tag."
    required: false
    default: 'release'
  clean:
    description: "Workflow file extensions to be cleaned before update. No wildcards as they will be auto-expanded. Defaults to none."
    required: false
    default: '.yaml'
outputs:
  old:
    description: "old version of workflows"
    value: "${{ steps.update.outputs.old }}"
  new:
    description: "new version of workflows"
    value: "${{ steps.update.outputs.new }}"
  date:
    description: "date of the most recent update attempt"
    value: "${{ steps.update.outputs.date }}"
runs:
  using: "composite"
  steps:
    - name: "Update Workflows"
      id: update
      run: |
        ${{ github.action_path }}/update-workflows.sh \
          ${{ inputs.version }} \
          ${{ inputs.clean }}
      shell: bash
