name: 'renv-checks'
description: 'Action to check if a repository is using renv and to generate a hashsum of the lockfile'
author: 'Robert P. Davey'
inputs:
  WORKBENCH_TAG:
    description: 'Override Workbench version tag, e.g. "v0.15.0" or "latest". Defaults to "latest".'
    required: false
    default: 'latest'
  CACHE_VERSION:
    description: 'Optional renv cache version override'
    required: false
    default: ''
  LESSON_PATH:
    description: 'Path to the lesson directory within the container. Defaults to "/home/rstudio/lesson".'
    default: '/home/rstudio/lesson'
  skip-cache-check:
    description: 'Skip checking for cache availability and just report if renv is needed'
    required: false
    default: false
    type: boolean
  role-to-assume:
    required: false
    type: string
  aws-region:
    required: false
    type: string
outputs:
  renv-needed:
    description: 'Is renv needed?'
    value: ${{ steps.check-for-renv.outputs.renv-exists }}
  renv-cache-hashsum:
    description: 'renv cache hashsum'
    value: ${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}
  renv-cache-available:
    description: 'Is the renv cache available?'
    value: ${{ steps.restore-renv-cache.outputs.cache-hit }}
  backup-cache-used:
    description: 'Was a previous cache version retrieved?'
    value: ${{ steps.restore-renv-cache.outputs.cache-hit != 'true' && steps.restore-renv-cache.outputs.cache-matched-key != '' }}

runs:
  using: "composite"
  steps:
    - name: "Checkout Lesson"
      uses: actions/checkout@v4

    - name: "Check for renv"
      id: check-for-renv
      run: |
        echo "::group::Checking if renv is used"
        if [[ -d renv ]]; then
          echo "✅ renv requirement found."
          echo "renv-exists=true" >> $GITHUB_OUTPUT
        else
          echo "❗No renv requirement found. Skipping..."
          echo "renv-exists=false" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"
      shell: bash

    - name: Calculate renv hash
      id: set-renv-hash
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' }}
      run: |
        echo "::group::Calculate renv cache hashsum"
        CACHE_VERSION_INPUT="${{ inputs.CACHE_VERSION }}"
        if [ -z "$CACHE_VERSION_INPUT" ]; then
          echo "renv-cache-hashsum=${{ hashFiles('renv/profiles/lesson-requirements/renv.lock') }}" >> $GITHUB_OUTPUT
        else
          echo "renv-cache-hashsum=$CACHE_VERSION_INPUT" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"
      shell: bash

    - name: Get Container Version Used
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' }}
      id: wb-vers
      uses: carpentries/actions/container-version@main
      with:
        WORKBENCH_TAG: ${{ inputs.WORKBENCH_TAG || 'latest' }}

    - name: "Validate Current Org and Workflow"
      id: validate-org-workflow
      uses: carpentries/actions/validate-org-workflow@frog-s3-test-1
      with:
        repo: ${{ github.repository }}
        workflow: ${{ github.workflow }}

    - name: Configure AWS credentials via OIDC
      id: aws-creds
      if: ${{ steps.validate-org-workflow.outputs.is_valid == 'true'  && inputs.skip-cache-check != 'true' }}
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        output-credentials: true

    - name: Restore renv from cache
      id: restore-renv-cache
      uses: tespkg/actions-cache/restore@v1.9.0
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' && inputs.skip-cache-check != 'true' }}
      with:
        # insecure: false # optional, use http instead of https. default false
        accessKey: ${{ steps.aws-creds.outputs.aws-access-key-id }}
        secretKey: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
        sessionToken: ${{ steps.aws-creds.outputs.aws-session-token }}
        bucket: workbench-docker-caches
        path: |
          /home/rstudio/lesson/renv
          /usr/local/lib/R/site-library
        key: ${{ github.repository }}-${{ steps.wb-vers.outputs.container-version }}-renv-${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}
        restore-keys: |
          ${{ github.repository }}-${{ steps.wb-vers.outputs.container-version }}-renv-
