name: 'renv-checks'
description: 'Action to check if a repository is using renv and to generate a hashsum of the lockfile'
author: 'Robert P. Davey'
inputs:
  WORKBENCH_TAG:
    description: 'Override Workbench version tag, e.g. "v0.15.0" or "latest". Defaults to "latest".'
    required: false
    default: 'latest'
  CACHE_VERSION:
    description: 'Optional renv cache version override'
    required: false
    default: ''
  LESSON_PATH:
    description: 'Path to the lesson directory within the container. Defaults to "/home/rstudio/lesson".'
    default: '/home/rstudio/lesson'
  skip-cache-check:
    description: 'Skip checking for cache availability and just report if renv is needed'
    required: false
    default: false
    type: boolean
  token:
    description: "GitHub PAT, usually passed as 'secrets.GITHUB_TOKEN' from the caller workflow. Required if skip-cache-check is false."
    required: false
  role-to-assume:
    required: false
    type: string
  aws-region:
    required: false
    type: string
outputs:
  renv-needed:
    description: 'Is renv needed?'
    value: ${{ steps.check-for-renv.outputs.renv-exists }}
  renv-cache-hashsum:
    description: 'renv cache hashsum'
    value: ${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}
  renv-cache-available:
    description: 'Is the renv cache available?'
    value: ${{ steps.restore-renv-cache.outputs.cache-hit }}
  cache-matched-key:
    description: 'The matched cache key, if any'
    value: ${{ steps.restore-renv-cache.outputs.cache-matched-key }}
  cache-matched-size:
    description: 'The matched cache size, if any'
    value: ${{ steps.restore-renv-cache.outputs.cache-size }}
  backup-cache-used:
    description: 'Was a previous cache version retrieved?'
    value: ${{ steps.restore-renv-cache.outputs.cache-hit != 'true' && ((steps.restore-renv-cache.outputs.cache-matched-key || '') != '') }}

runs:
  using: "composite"
  steps:
    - name: "Checkout Lesson"
      uses: actions/checkout@v4

    - name: "Check for renv"
      id: check-for-renv
      run: |
        # Checking if renv is used #
        if [[ -d renv ]]; then
          echo "âœ… renv requirement found."
          echo "renv-exists=true" >> $GITHUB_OUTPUT
        else
          echo "â—No renv requirement found. Skipping..."
          echo "renv-exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Calculate renv hash
      id: set-renv-hash
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' }}
      run: |
        # Calculating renv cache hashsum #
        CACHE_VERSION_INPUT="${{ inputs.CACHE_VERSION }}"
        if [[ -z "$CACHE_VERSION_INPUT" ]]; then
          echo "renv-cache-hashsum=${{ hashFiles('renv/profiles/lesson-requirements/renv.lock') }}" >> $GITHUB_OUTPUT
        else
          echo "renv-cache-hashsum=$CACHE_VERSION_INPUT" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Get Container Version Used
      id: wb-vers
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' && inputs.skip-cache-check != 'true' }}
      uses: carpentries/actions/container-version@main
      with:
        WORKBENCH_TAG: ${{ inputs.WORKBENCH_TAG || 'latest' }}
        renv-needed: ${{ steps.check-for-renv.outputs.renv-exists }}
        token: ${{ inputs.token }}

    - name: "Validate Current Org and Workflow"
      id: validate-org-workflow
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' && inputs.skip-cache-check != 'true' }}
      uses: carpentries/actions/validate-org-workflow@main
      with:
        repo: ${{ github.repository }}
        workflow: ${{ github.workflow }}

    - name: Configure AWS credentials via OIDC
      id: aws-creds
      if: |
        steps.validate-org-workflow.outputs.is_valid == 'true' &&
        inputs.skip-cache-check != 'true' &&
        inputs.role-to-assume != '' &&
        inputs.aws-region != ''
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        output-credentials: true

    - name: Restore renv from cache
      id: restore-renv-cache
      uses: carpentries/actions-cache/restore@frog-matchedkey-1
      if: ${{ steps.check-for-renv.outputs.renv-exists == 'true' && inputs.skip-cache-check != 'true' }}
      with:
        accessKey: ${{ steps.aws-creds.outputs.aws-access-key-id }}
        secretKey: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
        sessionToken: ${{ steps.aws-creds.outputs.aws-session-token }}
        bucket: workbench-docker-caches
        path: |
          /home/rstudio/lesson/renv
          /usr/local/lib/R/site-library
        key: ${{ github.repository }}/${{ steps.wb-vers.outputs.container-version }}_renv-${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}
        restore-keys: |
          ${{ github.repository }}/${{ steps.wb-vers.outputs.container-version }}_renv-

    - name: "Debug output"
      run: |
        # ðŸ’¡ Debug renv cache output #
        echo "renv-needed: ${{ steps.check-for-renv.outputs.renv-exists }}"
        echo "renv-cache-hashsum: ${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}"
        echo "renv-cache-available: ${{ steps.restore-renv-cache.outputs.cache-hit }}"
        echo "cache-matched-key: ${{ steps.restore-renv-cache.outputs.cache-matched-key }}"
        echo "cache-matched-size: ${{ steps.restore-renv-cache.outputs.cache-size }}"
        echo "backup-cache-used: ${{ steps.restore-renv-cache.outputs.cache-hit != 'true' && ((steps.restore-renv-cache.outputs.cache-matched-key || '') != '') }}"
      shell: bash

    - name: List renv caches in S3
      id: list-s3-renv-caches
      if: |
        steps.check-for-renv.outputs.renv-exists == 'true' &&
        inputs.skip-cache-check != 'true' &&
        inputs.role-to-assume != '' &&
        inputs.aws-region != ''
      run: |
        # â„¹ï¸ Available renv caches #
        set +e
        caches=$(aws s3 ls s3://workbench-docker-caches/${{ github.repository }}/ --recursive 2>&1)
        exit_code=$?
        set -e

        if [ -z "$caches" ]; then
          echo "## âš ï¸ No renv caches found in S3" >> $GITHUB_STEP_SUMMARY
          echo "No renv caches are currently stored for this lesson repository." >> $GITHUB_STEP_SUMMARY
          echo "This is normal if you haven't yet had a successful build that created a cache." >> $GITHUB_STEP_SUMMARY
          exit 0
        else
          table=$(echo "$caches" | awk '{split($4,a,"/"); split(a[3],b,"_"); split(b[2],c,"-"); print "| " $1 " " $2 " | " b[1] " | " c[2] " |"}')
        fi

        if [ -n "${{ steps.restore-renv-cache.outputs.cache-matched-key }}" ]; then
          echo "## âœ… renv cache found in S3" >> $GITHUB_STEP_SUMMARY
          echo "This build will use the following renv cache: ${{ steps.wb-vers.outputs.container-version }} ${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}" >> $GITHUB_STEP_SUMMARY
        fi

        if [ -n "$table" ]; then
          echo "## â„¹ï¸ Available renv caches" >> $GITHUB_STEP_SUMMARY
          echo "The following renv caches are available for this lesson:" >> $GITHUB_STEP_SUMMARY
          echo "| date | container version | renv hashkey |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "$table" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
