name: 'Check Valid Pull Request'
description: 'Checks that a Pull request is open and that it does not contain any .github files'
inputs:
  pr:  # id of input
    description: 'pull request number'
    required: true
  sha:
    description: 'sha of the latest head'
    required: false
    default: null
  headroom:
    description: 'number of commits for sha to be found'
    required: false
    default: 1
  repo:
    description: 'github repository (default: current repository)'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  invalid:
    description: 'sha of an invalid commit hash'
    required: false
    default: null
  fail_on_error: 
    description: 'flag inidicating if this action should set a failed status on error'
    required: false
    default: false
outputs:
  VALID: 
    description: "flag indicating if the PR is valid. 'true' if valid, 'false' otherwise"
  payload:
    description: "the JSON from the pull request call"
  MSG:
    description: "a message that can be sent to the PR in the case of an invalid PR"
runs:
  using: 'node20'
  main: 'index.js'
