name: 'setup-sandpaper'
description: 'Action to setup The Carpentries Lesson Infrastructure'
author: 'Zhian N. Kamvar'
inputs:
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache'
    required: true
    default: 1
  sandpaper-version: 
    description: 'The version of sandpaper to use. You can use the remotes syntax to specify a version to use. Defaults to latest on the r-universe.'
    default: 'latest'
  pegboard-version: 
    description: 'The version of pegboard to use. You can use the remotes syntax to specify a version to use. Defaults to latest on the r-universe.'
    default: 'latest'
  varnish-version: 
    description: 'The version of varnish to use. You can use the remotes syntax to specify a version to use. Defaults to latest on the r-universe.'
    default: 'latest'
runs:
  using: "composite"
  steps:
      - name: Install pak and query dependencies
        run: |
          cat("::group::Register Repositories\n")
          on_linux <- Sys.info()[["sysname"]] == "Linux"
          if (on_linux) {
            if (Sys.getenv("RSPM") == "") {
              release <- system("lsb_release -c | awk '{print $2}'", intern = TRUE)
              Sys.setenv("RSPM" = 
                paste0("https://packagemanager.posit.co/all/__linux__/", release, "/latest"))
            }
          }
          repos <- list(
            RSPM        = Sys.getenv("RSPM"),
            carpentries = "https://carpentries.r-universe.dev/",
            CRAN        = "https://cran.rstudio.com"
          )
          options(pak.no_extra_messages = TRUE, repos = repos)
          cat("Repositories Used")
          print(getOption("repos"))
          cat("::endgroup::\n")

          cat("::group::Install remotes\n")
          install.packages('remotes')
          sand_deps <- remotes::package_deps("sandpaper")
          varn_deps <- remotes::package_deps("varnish")
          sess_deps <- remotes::package_deps("sessioninfo")
          with_deps <- remotes::package_deps("withr")
          deps      <- rbind(sand_deps, varn_deps, sess_deps, with_deps)
          saveRDS(deps, ".github/r-depends.rds")
          cat("::group::Install remotes\n")
        shell: Rscript {0}

      - name: Get R and OS version
        id: get-version
        run: |
          cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
          cat("r-version=", if (grepl("development", rv <- R.Version()$version.string)) as.character(getRversion()) else rv, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
        shell: Rscript {0}

      - name: Install apt dependencies for Ubuntu
        id: run-apt
        shell: bash
        run: |
          sudo apt update || exit 0
          curl https://carpentries.r-universe.dev/stats/sysdeps 2> /dev/null \
          | jq -r '.headers[0] | select(. != null)' 2> /dev/null \
          > ${{ runner.temp }}/sysdeps.txt
          if [[ `wc -l < ${{ runner.temp }}/sysdeps.txt` -gt 0 ]]; then
            echo 'sysdeps acquired'
          else
            echo 'fetching sysdeps from descriptions'
            curl https://carpentries.r-universe.dev/stats/descriptions \
            | jq -r '._builder.sysdeps | .[].headers | select(. != null)' 2> /dev/null \
            > ${{ runner.temp }}/sysdeps.txt
          fi
          if [[ `wc -l < ${{ runner.temp }}/sysdeps.txt` -eq 0 ]]; then
            echo "::warn::System dependencies could not be acquired. Builds may fail"
            exit 1
          else
            echo "found sysdeps: $(cat ${{ runner.temp }}/sysdeps.txt)"
          fi
          printf "libxslt-dev\n" >> ${{ runner.temp }}/sysdeps.txt
          sudo xargs apt-get install --fix-missing -y < ${{ runner.temp }}/sysdeps.txt || echo "Not on Ubuntu"

      - name: Restore R package cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: WORKBENCH-${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: WORKBENCH-${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-

      - name: Install dependencies
        run: |
          cat("::group::Register Repositories\n")
          on_linux <- Sys.info()[["sysname"]] == "Linux"
          if (on_linux) {
            if (Sys.getenv("RSPM") == "") {
              release <- system("lsb_release -c | awk '{print $2}'", intern = TRUE)
              Sys.setenv("RSPM" = 
                paste0("https://packagemanager.posit.co/all/__linux__/", release, "/latest"))
            }
          }
          repos <- list(
            RSPM        = Sys.getenv("RSPM"),
            carpentries = "https://carpentries.r-universe.dev/",
            CRAN        = "https://cran.rstudio.com"
          )
          options(pak.no_extra_messages = TRUE, repos = repos)
          cat("Repositories Used")
          print(getOption("repos"))
          cat("::endgroup::\n")

          cat("::group::Install dependencies\n")
          on_linux <- Sys.info()[["sysname"]] == "Linux"
          library("remotes")
          sand_deps <- remotes::package_deps("sandpaper")
          varn_deps <- remotes::package_deps("varnish")
          sess_deps <- remotes::package_deps("sessioninfo")
          with_deps <- remotes::package_deps("withr")
          pkgs      <- rbind(sand_deps, varn_deps, sess_deps, with_deps)
          print(pkgs)
          update(pkgs, upgrade = "always")
          cat("::endgroup::\n")
          varnish_version   <- '${{ inputs.varnish-version }}'
          sandpaper_version <- '${{ inputs.sandpaper-version }}'
          pegboard_version  <- '${{ inputs.pegboard-version }}'
          cfg <- if (file.exists("config.yaml")) readLines("config.yaml") else character(0)
          get_version <- function(x, key = "varnish") {
            res <- x[grepl(paste0("^", key, "\\s?:"), x)]
            if (length(res)) {
              res <- trimws(strsplit(res, ":")[[1]][2])
              # trim quotes
              res <- gsub("[\"']", "", res)
              if (grepl("^[0-9]", res)) {
                res <- paste0("carpentries/", key, "@", res)
              }
            } else {
              res <- "latest"
            }
            res
          }
          varnish_version <- get_version(cfg, key = "varnish")
          sandpaper_version <- get_version(cfg, key = "sandpaper")
          pegboard_version <- get_version(cfg, key = "pegboard")
          if (varnish_version != "latest") {
            cat("::group::Installing", varnish_version, "\n")
            install_github(varnish_version)
            cat("::endgroup::\n")
          }
          if (sandpaper_version != "latest") {
            cat("::group::Installing", sandpaper_version, "\n")
            install_github(sandpaper_version)
            cat("::endgroup::\n")
          }
          if (pegboard_version != "latest") {
            cat("::group::Installing", pegboard_version, "\n")
            install_github(pegboard_version)
            cat("::endgroup::\n")
          }
        shell: Rscript {0}

      - name: Session info
        run: |
          cat("::group::Session info\n")
          sandpaper:::ci_session_info()
          cat("::endgroup::\n")
        shell: Rscript {0}

      - name: Don't use tar 1.30 from Rtools35 to store the cache
        shell: bash
        run: |
          if command -v /c/Rtools/bin/tar && /c/Rtools/bin/tar --version | grep -q 'tar (GNU tar) 1.30'
            then echo 'C:/Program Files/Git/usr/bin' >> $GITHUB_PATH
          fi
