name: 'download a workflow artifact'
description: 'This does what it says. It download a specific artifact given a workflow number'
inputs:
  run:  # id of input
    description: 'workflow run number'
    required: true
  name:
    description: 'name of the artifact'
    required: true
  dir:
    description: 'directory to dump the artifact (default: current workspace)'
    required: false
    default: ${{ github.workspace }}
  repo:
    description: 'github repository (default: current repository)'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
outputs:
  success:
    description: "a boolean variable if the download was successful (true) or not (false)"
runs:
  using: 'node16'
  main: 'index.js'
