name: 'record-container-version'
description: 'Action to record the Docker container version in workbench-docker-version.txt'
author: 'Robert P. Davey'
inputs:
  CONTAINER_VER:
    description: 'Docker container version used'
    required: true
  token:
    description: "Token to validate"
    required: false
  role-to-assume:
    required: false
  aws-region:
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout Lesson"
      uses: actions/checkout@v4

    - name: "Validate Current Org and Workflow"
      id: validate-org-workflow
      uses: carpentries/actions/validate-org-workflow@frog-s3-test-1
      with:
        repo: ${{ github.repository }}
        workflow: ${{ github.workflow }}

    - name: Configure AWS credentials via OIDC
      id: aws-creds
      if: ${{ steps.validate-org-workflow.outputs.is_valid == 'true' }}
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: "Set PAT from AWS Secrets Manager"
      if: ${{ steps.validate-org-workflow.outputs.is_valid == 'true' }}
      id: set-pat
      run: |
        # Setting AWS PAT #
        SECRET=$(aws secretsmanager get-secret-value \
                  --secret-id carpentries-bot/github-pat \
                  --query SecretString --output text)
        PAT=$(echo "$SECRET" | jq -r .[])
        echo "::add-mask::$PAT"
        echo "pat=$PAT" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: "Validate token"
      id: validate-token
      uses: carpentries/actions/check-valid-credentials@main
      with:
        token: ${{ steps.set-pat.outputs.pat || inputs.token }}

    - name: Record Container Version Used
      id: record-wb-vers
      run: |
        # Recording container version to .github/workbench-docker-version.txt #
        echo "${{ inputs.CONTAINER_VER }}" > .github/workbench-docker-version.txt
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .github/workbench-docker-version.txt
        if [ ! -z "$(git status --porcelain)" ]; then
          echo "create-pr=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Create Workbench Version PR
      uses: peter-evans/create-pull-request@v7.0.8
      id: cpr
      if: |
        steps.record-wb-vers.outputs.create-pr == 'true'
      with:
        token: ${{ steps.set-pat.outputs.pat || inputs.token }}
        branch: "update/workbench-docker-version"
        delete-branch: true
        commit-message: "[actions] update workbench docker version to ${{ inputs.CONTAINER_VER }}"
        title: "Update workbench docker version to ${{ inputs.CONTAINER_VER }}"
        body: |
          Workbench Docker image version updated to: [${{ inputs.CONTAINER_VER }}][1]

          This will trigger a rebuild.

          [1]: "https://hub.docker.com/layers/carpentries/workbench-docker/${{ inputs.CONTAINER_VER }}"
        labels: "type: docker version"
        draft: false

    - name: Auto-merge Workbench Version PR
      if: steps.record-wb-vers.outputs.create-pr == 'true' && steps.cpr.outcome == 'success'
      run: |
        # Auto-merging PR #
        gh pr merge --auto --squash update/workbench-docker-version
      env:
        GH_TOKEN: ${{ steps.set-pat.outputs.pat || inputs.token }}
      shell: bash

    # thanks @Bisaloo! - https://github.com/carpentries/sandpaper/issues/646#issuecomment-2829578435
    # only trigger checks manually if the validate-token step had no valid AWS or SANDPAPER_WORKFLOW token
    - name: "Trigger checks"
      if: ${{ steps.cpr.outputs.pull-request-number != '' && steps.validate-token.outputs.wf != 'true'}}
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        # ⚠️ WARNING: No valid SANDPAPER_WORKFLOW token set #
        echo "## ⚠️ WARNING: No valid SANDPAPER_WORKFLOW token set" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "This lesson build is running outside the Carpentries organisation, and you do not have a valid SANDPAPER_WORKFLOW Personal Access Token (PAT) available within this repository secrets." >> $GITHUB_STEP_SUMMARY
        echo "Therefore, the PR check workflow is being triggered manually." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "To avoid seeing this message, we recommend adding a SANDPAPER_WORKFLOW PAT to your repository!" >> $GITHUB_STEP_SUMMARY

        gh workflow run pr-comment.yaml --field workflow_id=${{ github.run_id }}
      shell: bash
