name: Test check-valid-pr

on: 
  push:
    paths: ['.github/workflows/test-check-valid-pr.yaml', 'check-valid-pr/**']

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Testing PR states
    steps:
      - uses: actions/checkout@v4
      - id: valid-pr
        name: "Valid PR"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 4
          sha: '7237b06c519da8d35dd825df76785aacb1ae519e'
      - run: |
          echo ${{ steps.valid-pr.outputs.payload }}
      - id: spoofed-pr
        name: "Spoofed PR"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 3
          sha: '7237b06c519da8d35dd825df76785aacb1ae519e'
      - run: |
          echo ${{ steps.spoofed-pr.outputs.payload }}
      - id: invalid-pr
        name: "Invalid PR"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 6
          sha: 'f36adb8cb9816496a5636d841952ec0caaea2c1b'
      - run: |
          echo VALID? ${{ steps.invalid-pr.outputs.VALID }}
          echo ${{ steps.invalid-pr.outputs.payload }}
      - id: invalid-pr-closed
        name: "Invalid PR (status)"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 227
          repo: 'grunwaldlab/poppr'
      - run: |
          echo VALID? ${{ steps.invalid-pr.outputs.VALID }}
          echo ${{ steps.invalid-pr-files.outputs.payload }}
      - id: invalid-pr-files
        name: "Invalid PR (files)"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 228
          repo: 'grunwaldlab/poppr'
      - run: |
          echo VALID? ${{ steps.invalid-pr.outputs.VALID }}
          echo ${{ steps.invalid-pr-closed.outputs.payload }}
      - id: closed
        name: "Closed PR"
        uses: carpentries/actions/check-valid-pr@main
        with:
          pr: 21
          repo: 'zkamvar/testme'
      - run: |
          echo VALID? ${{ steps.invalid-pr.outputs.VALID }}
          echo ${{ steps.closed.outputs.payload }}
