name: Test Check Credentials
on: 
  push:
    paths: ['.github/workflows/test-check-credentials.yaml', 'check-valid-credentials/**']
jobs:
  check_token:
    name: "Check GitHub Token"
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check.outputs.wf }}
      repo:  ${{ steps.check.outputs.repo }}
      svalid: ${{ steps.sandpaper.outputs.wf }}
      srepo:  ${{ steps.sandpaper.outputs.repo }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Validate Token"
        id: check
        uses: ./check-valid-credentials
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Validate Sandpaper Token"
        id: sandpaper
        uses: ./check-valid-credentials
        with:
          token: ${{ secrets.SANDPAPER_WORKFLOW }}
  
  always_runs:
    name: "Alert Bad Token"
    runs-on: ubuntu-latest
    needs: check_token
    if: ${{ needs.check_token.outputs.valid != 'true' }}
    steps:
      - name: "The GITHUB_TOKEN has no workflow scope"
        run: |
          echo ${{ needs.check_token.outputs.valid }}
          echo ${{ needs.check_token.outputs.repo }}
          echo ${{ needs.check_token.outputs.svalid }}
          echo ${{ needs.check_token.outputs.srepo }}
          echo "::warning::The GITHUB_TOKEN workflow scope is not valid"
      - name: "The GITHUB_TOKEN has a repo scope"
        if: ${{ needs.check_token.outputs.repo == 'true' }}
        run: echo "The GITHUB_TOKEN repo scope is valid"

  never_runs:
    name: "I will never run"
    runs-on: ubuntu-latest
    needs: check_token
    if: ${{ needs.check_token.outputs.valid == 'true' }}
    steps:
      - name: "Doesn't run"
        run: echo "::error::I SHOULD NOT EXIST"

