name: Test Check Credentials
on: 
  push:
    paths: ['.github/workflows/test-check-credentials.yaml', 'check-valid-credentials/**']
jobs:
  check_token:
    name: "Check GitHub Token"
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check.outputs.wf }}
    steps:
      - name: "Validate Token"
        id: check
        uses: carpentries/actions/check-valid-credentials@check-credenitals
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  bad_token:
    name: "Alert Bad Token"
    runs-on: ubuntu-latest
    needs: check_token
    if: ${{ needs.check_token.outputs.valid != 'true' }}
    steps:
      - name: "Warn"
        run: echo "::warning::The GITHUB_WORKFLOW token is not valid"
